name: Generate S3 Presigned URLs

on:
  workflow_dispatch:
    inputs:
      bucket:
        description: "S3 bucket name"
        required: true
      keys:
        description: "Comma-separated list of S3 object keys (file paths)"
        required: true
      action:
        description: "Operation: get (download) or put (upload)"
        required: true
        default: "get"
      expiry:
        description: "Expiry time in seconds"
        required: false
        default: "3600"

jobs:
  presign:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ vars.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.S3_BUCKET_NAME }}

      - name: Generate presigned URLs
        id: presign
        run: |
          echo "✅ Generating pre-signed URLs for action=${{ github.event.inputs.action }}"
          echo "" > urls.txt
          
          IFS=',' read -ra KEYS <<< "${{ github.event.inputs.keys }}"
          for key in "${KEYS[@]}"; do
            key=$(echo $key | xargs) # trim spaces
            if [ "${{ github.event.inputs.action }}" = "put" ]; then
              url=$(aws s3 presign s3://${{ github.event.inputs.bucket }}/$key \
                --expires-in ${{ github.event.inputs.expiry }} \
                --http-method PUT)
              echo "PUT URL for $key:" | tee -a urls.txt
            else
              url=$(aws s3 presign s3://${{ github.event.inputs.bucket }}/$key \
                --expires-in ${{ github.event.inputs.expiry }})
              echo "GET URL for $key:" | tee -a urls.txt
            fi
            echo "$url" | tee -a urls.txt
            echo "" | tee -a urls.txt
          done

      - name: Upload all URLs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: presigned-urls
          path: urls.txt
